# Generated by Django 6.0.3 on 2026-03-20 14:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_full_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_role', models.CharField(max_length=50)),
                ('action_type', models.CharField(choices=[('STOCK_IN', 'Stock In'), ('STOCK_OUT', 'Stock Out'), ('BLACKLISTED', 'Blacklisted'), ('RESTORED', 'Restored'), ('QUARANTINED', 'Quarantined'), ('ORDER_CREATED', 'Order Created')], max_length=20)),
                ('product_name', models.CharField(max_length=255)),
                ('product_sku', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
