# Generated by Django 6.0.3 on 2026-03-20 13:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prodotti', '0004_product_blacklist_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_full_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_role', models.CharField(max_length=50)),
                ('action_type', models.CharField(choices=[('STOCK_IN', 'Stock In'), ('STOCK_OUT', 'Stock Out'), ('BLACKLISTED', 'Blacklisted'), ('RESTORED', 'Restored'), ('QUARANTINED', 'Quarantined'), ('ORDER_CREATED', 'Order Created')], max_length=20)),
                ('product_name', models.CharField(max_length=255)),
                ('product_sku', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='prodotti.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='auditlog_au_timesta_a26c2b_idx'), models.Index(fields=['user'], name='auditlog_au_user_id_08ad03_idx'), models.Index(fields=['product'], name='auditlog_au_product_b42a16_idx'), models.Index(fields=['action_type'], name='auditlog_au_action__ef1bd4_idx')],
            },
        ),
    ]
