# Generated by Django 6.0.3 on 2026-03-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornitori', '0001_initial'),
        ('prodotti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='products', to='fornitori.supplier'),
        ),
    ]
