# Generated by Django 6.0.3 on 2026-03-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0002_alter_product_suppliers'),
        ('prodotti', '0004_product_blacklist_fields'),
    ]

    operations = [
    ]
