# Generated by Django 6.0.3 on 2026-03-20 14:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('vat_number', models.CharField(blank=True, max_length=50)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address_street', models.CharField(blank=True, max_length=255)),
                ('address_city', models.CharField(blank=True, max_length=100)),
                ('address_country', models.CharField(blank=True, default='Italia', max_length=100)),
                ('address_zip', models.CharField(blank=True, max_length=20)),
                ('payment_terms', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
