# Generated by Django 6.0.3 on 2026-03-19 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movimenti', '0001_initial'),
        ('prodotti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='prodotti.productlot'),
        ),
    ]
